site_name: Quattor Documentation

theme: 'readthedocs'

pages:
- introduction: 'index.md'
- CAF:
    - filereader: CAF/filereader.md
    - process: CAF/process.md
    - reporter: CAF/reporter.md
    - kerberos: CAF/kerberos.md
    - log: CAF/log.md
    - rulebasededitor: CAF/rulebasededitor.md
    - objecttext: CAF/objecttext.md
    - application: CAF/application.md
    - object: CAF/object.md
    - service: CAF/service.md
    - filewriter: CAF/filewriter.md
    - history: CAF/history.md
    - path: CAF/path.md
    - reportermany: CAF/reportermany.md
    - fileeditor: CAF/fileeditor.md
    - lock: CAF/lock.md
    - textrender: CAF/textrender.md
- CCM:
    - db: CCM/db.md
    - element: CCM/element.md
    - jsonprofilesimple: CCM/jsonprofilesimple.md
    - path: CCM/path.md
    - cli: CCM/cli.md
    - fetch::download: CCM/fetch::download.md
    - fetch::profilecache: CCM/fetch::profilecache.md
    - ccfg: CCM/ccfg.md
    - jsonprofiletyped: CCM/jsonprofiletyped.md
    - xmlpanprofile: CCM/xmlpanprofile.md
    - fetch: CCM/fetch.md
    - tt::scalar: CCM/tt::scalar.md
    - resource: CCM/resource.md
    - options: CCM/options.md
    - configuration: CCM/configuration.md
    - fetch::config: CCM/fetch::config.md
    - cachemanager: CCM/cachemanager.md
    - textrender: CCM/textrender.md
- components:
    - openvpn::schema: components/openvpn::schema.md
    - nsca: components/nsca.md
    - profile::functions: components/profile::functions.md
    - download: components/download.md
    - directoryservices::schema: components/directoryservices::schema.md
    - gpfs: components/gpfs.md
    - spma::software: components/spma::software.md
    - network::core-schema: components/network::core-schema.md
    - ssh: components/ssh.md
    - nsca::schema: components/nsca::schema.md
    - ganglia: components/ganglia.md
    - postfix: components/postfix.md
    - chkconfig::schema: components/chkconfig::schema.md
    - sysconfig: components/sysconfig.md
    - ofed::schema: components/ofed::schema.md
    - aiiserver: components/aiiserver.md
    - systemd::service::chkconfig: components/systemd::service::chkconfig.md
    - icinga::schema: components/icinga::schema.md
    - hostsaccess::schema: components/hostsaccess::schema.md
    - ipmi: components/ipmi.md
    - ceph::schema-mds: components/ceph::schema-mds.md
    - mysql: components/mysql.md
    - ipmi::schema: components/ipmi::schema.md
    - spma: components/spma.md
    - freeipa::schema: components/freeipa::schema.md
    - opennebula::commands: components/opennebula::commands.md
    - authconfig::sssd::sasl: components/authconfig::sssd::sasl.md
    - authconfig::sssd: components/authconfig::sssd.md
    - interactivelimits: components/interactivelimits.md
    - authconfig::schema: components/authconfig::schema.md
    - metaconfig::schema: components/metaconfig::schema.md
    - syslog::schema: components/syslog::schema.md
    - syslog: components/syslog.md
    - pam::schema: components/pam::schema.md
    - spma::functions: components/spma::functions.md
    - altlogrotate: components/altlogrotate.md
    - symlink: components/symlink.md
    - nss::schema: components/nss::schema.md
    - sendmail: components/sendmail.md
    - nfs::schema: components/nfs::schema.md
    - filecopy::schema: components/filecopy::schema.md
    - postfix::schema: components/postfix::schema.md
    - filecopy: components/filecopy.md
    - authconfig::sssd::ldap: components/authconfig::sssd::ldap.md
    - spma::schema: components/spma::schema.md
    - cron::schema: components/cron::schema.md
    - nagios::functions: components/nagios::functions.md
    - sendmail::schema: components/sendmail::schema.md
    - puppet::schema: components/puppet::schema.md
    - ceph::crushmap: components/ceph::crushmap.md
    - grub: components/grub.md
    - autofs::schema: components/autofs::schema.md
    - iptables::schema: components/iptables::schema.md
    - nscd::schema: components/nscd::schema.md
    - amandaserver::schema: components/amandaserver::schema.md
    - gmond::schema: components/gmond::schema.md
    - ceph: components/ceph.md
    - amandaserver: components/amandaserver.md
    - gmetad: components/gmetad.md
    - symlink::schema: components/symlink::schema.md
    - systemd::service::unit: components/systemd::service::unit.md
    - directoryservices: components/directoryservices.md
    - fstab::schema: components/fstab::schema.md
    - freeipa: components/freeipa.md
    - shorewall::schema: components/shorewall::schema.md
    - fmonagent: components/fmonagent.md
    - accounts::functions: components/accounts::functions.md
    - freeipa::user: components/freeipa::user.md
    - spma::yumng: components/spma::yumng.md
    - chkconfig: components/chkconfig.md
    - filesystems: components/filesystems.md
    - sudo: components/sudo.md
    - pam: components/pam.md
    - spma::yumng::schema: components/spma::yumng::schema.md
    - freeipa::nss: components/freeipa::nss.md
    - authconfig::sssd::ipa: components/authconfig::sssd::ipa.md
    - nrpe: components/nrpe.md
    - pnp4nagios::schema: components/pnp4nagios::schema.md
    - modprobe::schema: components/modprobe::schema.md
    - download::schema: components/download::schema.md
    - nrpe::schema: components/nrpe::schema.md
    - ssh::schema: components/ssh::schema.md
    - spma::ips: components/spma::ips.md
    - grub::schema: components/grub::schema.md
    - mcx: components/mcx.md
    - authconfig: components/authconfig.md
    - named: components/named.md
    - ccm: components/ccm.md
    - resolver: components/resolver.md
    - ceph::schema: components/ceph::schema.md
    - etcservices: components/etcservices.md
    - afsclt: components/afsclt.md
    - fmonagent::schema: components/fmonagent::schema.md
    - hostsfile: components/hostsfile.md
    - ntpd::schema: components/ntpd::schema.md
    - nscd: components/nscd.md
    - systemd::systemctl: components/systemd::systemctl.md
    - openldap::schema: components/openldap::schema.md
    - ofed: components/ofed.md
    - useraccess: components/useraccess.md
    - mcx::schema: components/mcx::schema.md
    - gmond: components/gmond.md
    - freeipa::cert: components/freeipa::cert.md
    - systemd::service: components/systemd::service.md
    - dirperm::schema: components/dirperm::schema.md
    - accounts::schema: components/accounts::schema.md
    - afsclt::schema: components/afsclt::schema.md
    - cdp::schema: components/cdp::schema.md
    - accounts: components/accounts.md
    - hostsfile::schema: components/hostsfile::schema.md
    - openvpn: components/openvpn.md
    - dirperm: components/dirperm.md
    - fstab: components/fstab.md
    - aiiserver::schema: components/aiiserver::schema.md
    - spma-run: components/spma-run.md
    - hostsaccess: components/hostsaccess.md
    - sudo::functions: components/sudo::functions.md
    - profile: components/profile.md
    - nss: components/nss.md
    - libvirtd::schema: components/libvirtd::schema.md
    - puppet: components/puppet.md
    - opennebula::schema: components/opennebula::schema.md
    - ceph::compare: components/ceph::compare.md
    - cups::schema: components/cups::schema.md
    - ldconf: components/ldconf.md
    - opennebula: components/opennebula.md
    - icinga::functions: components/icinga::functions.md
    - systemd::unitfile: components/systemd::unitfile.md
    - resolver::schema: components/resolver::schema.md
    - network: components/network.md
    - ceph::daemon: components/ceph::daemon.md
    - ntpd: components/ntpd.md
    - cdp: components/cdp.md
    - systemd::functions: components/systemd::functions.md
    - freeipa::host: components/freeipa::host.md
    - postgresql: components/postgresql.md
    - ganglia::schema: components/ganglia::schema.md
    - useraccess::schema: components/useraccess::schema.md
    - sysctl::schema: components/sysctl::schema.md
    - ceph::schema-osd: components/ceph::schema-osd.md
    - gmetad::schema: components/gmetad::schema.md
    - authconfig::sssd::sudo: components/authconfig::sssd::sudo.md
    - authconfig::sssd::user: components/authconfig::sssd::user.md
    - sysctl: components/sysctl.md
    - modprobe: components/modprobe.md
    - iptables: components/iptables.md
    - syslogng: components/syslogng.md
    - pam::config: components/pam::config.md
    - profile::schema: components/profile::schema.md
    - authconfig::sssd::tls: components/authconfig::sssd::tls.md
    - ceph::schema-rgw: components/ceph::schema-rgw.md
    - systemd::service::component::chkconfig: components/systemd::service::component::chkconfig.md
    - network::schema: components/network::schema.md
    - systemd::schema: components/systemd::schema.md
    - ceph::commands: components/ceph::commands.md
    - filesystems::schema: components/filesystems::schema.md
    - openldap: components/openldap.md
    - mysql::schema: components/mysql::schema.md
    - sysconfig::schema: components/sysconfig::schema.md
    - libvirtd: components/libvirtd.md
    - freeipa::client: components/freeipa::client.md
    - freeipa::logger: components/freeipa::logger.md
    - cron: components/cron.md
    - spma::yum::schema: components/spma::yum::schema.md
    - nagios::schema: components/nagios::schema.md
    - nagios: components/nagios.md
    - ldconf::schema: components/ldconf::schema.md
    - named::schema: components/named::schema.md
    - ceph::config: components/ceph::config.md
    - metaconfig: components/metaconfig.md
    - nfs: components/nfs.md
    - pnp4nagios: components/pnp4nagios.md
    - interactivelimits::schema: components/interactivelimits::schema.md
    - freeipa::service: components/freeipa::service.md
    - spma::yum: components/spma::yum.md
    - altlogrotate::schema: components/altlogrotate::schema.md
    - ceph::schema-mon: components/ceph::schema-mon.md
    - spma::ips::schema: components/spma::ips::schema.md
    - systemd: components/systemd.md
    - freeipa::cli: components/freeipa::cli.md
    - autofs: components/autofs.md
    - ccm::schema: components/ccm::schema.md
    - syslogng::schema: components/syslogng::schema.md
    - gpfs::schema: components/gpfs::schema.md
    - freeipa::dns: components/freeipa::dns.md
    - aii::freeipa::schema: components/aii::freeipa::schema.md
    - etcservices::schema: components/etcservices::schema.md
    - icinga: components/icinga.md
    - freeipa::group: components/freeipa::group.md
    - postgresql::schema: components/postgresql::schema.md
    - sudo::schema: components/sudo::schema.md
    - cups: components/cups.md
- components-grid:
    - pbsserver: components-grid/pbsserver.md
    - globuscfg::schema: components-grid/globuscfg::schema.md
    - wlconfig::schema: components-grid/wlconfig::schema.md
    - lcgmonjob::schema: components-grid/lcgmonjob::schema.md
    - pbsserver::schema: components-grid/pbsserver::schema.md
    - myproxy: components-grid/myproxy.md
    - mkgridmap::schema: components-grid/mkgridmap::schema.md
    - gsissh: components-grid/gsissh.md
    - lcgbdii::schema: components-grid/lcgbdii::schema.md
    - xrootd::schema: components-grid/xrootd::schema.md
    - pbsclient: components-grid/pbsclient.md
    - condorconfig: components-grid/condorconfig.md
    - gip2::schema: components-grid/gip2::schema.md
    - dpmlfc::schema: components-grid/dpmlfc::schema.md
    - wmsclient: components-grid/wmsclient.md
    - maui::schema: components-grid/maui::schema.md
    - dcache::schema: components-grid/dcache::schema.md
    - lcgmonjob: components-grid/lcgmonjob.md
    - gridmapdir: components-grid/gridmapdir.md
    - wmsclient::schema: components-grid/wmsclient::schema.md
    - dpmlfc: components-grid/dpmlfc.md
    - wlconfig: components-grid/wlconfig.md
    - globuscfg: components-grid/globuscfg.md
    - glitestartup::schema: components-grid/glitestartup::schema.md
    - gacl::schema: components-grid/gacl::schema.md
    - condorconfig::schema: components-grid/condorconfig::schema.md
    - glitestartup: components-grid/glitestartup.md
    - dcache: components-grid/dcache.md
    - maui: components-grid/maui.md
    - wmslb::schema: components-grid/wmslb::schema.md
    - lcmaps: components-grid/lcmaps.md
    - vomsclient::schema: components-grid/vomsclient::schema.md
    - gridmapdir::schema: components-grid/gridmapdir::schema.md
    - lcmaps::schema: components-grid/lcmaps::schema.md
    - myproxy::schema: components-grid/myproxy::schema.md
    - lcas: components-grid/lcas.md
    - pbsknownhosts::schema: components-grid/pbsknownhosts::schema.md
    - lcgbdii: components-grid/lcgbdii.md
    - gsissh::schema: components-grid/gsissh::schema.md
    - lbconfig: components-grid/lbconfig.md
    - pbsclient::schema: components-grid/pbsclient::schema.md
    - glitestartup::functions: components-grid/glitestartup::functions.md
    - wmslb: components-grid/wmslb.md
    - lbconfig::schema: components-grid/lbconfig::schema.md
    - gacl: components-grid/gacl.md
    - gip2: components-grid/gip2.md
    - pbsknownhosts: components-grid/pbsknownhosts.md
    - vomsclient: components-grid/vomsclient.md
    - mkgridmap: components-grid/mkgridmap.md
    - xrootd: components-grid/xrootd.md
    - lcas::schema: components-grid/lcas::schema.md
