site_name: Quattor Documentation

theme: 'readthedocs'

pages:
- introduction: 'index.md'
- CAF:
    - application: 'CAF/application.md'
    - fileeditor: 'CAF/fileeditor.md'
    - filereader: 'CAF/filereader.md'
    - filewriter: 'CAF/filewriter.md'
    - kerberos: 'CAF/kerberos.md'
    - lock: 'CAF/lock.md'
    - log: 'CAF/log.md'
    - object: 'CAF/object.md'
    - objecttext: 'CAF/objecttext.md'
    - process: 'CAF/process.md'
    - reporter: 'CAF/reporter.md'
    - reportermany: 'CAF/reportermany.md'
    - service: 'CAF/service.md'
    - textrender: 'CAF/textrender.md'
- CCM:
    - cachemanager: 'CCM/cachemanager.md'
    - ccfg: 'CCM/ccfg.md'
    - cli: 'CCM/cli.md'
    - configuration: 'CCM/configuration.md'
    - db: 'CCM/db.md'
    - element: 'CCM/element.md'
    - fetch: 'CCM/fetch.md'
    - fetch::config: 'CCM/fetch::config.md'
    - fetch::download: 'CCM/fetch::download.md'
    - fetch::profilecache: 'CCM/fetch::profilecache.md'
    - jsonprofilesimple: 'CCM/jsonprofilesimple.md'
    - jsonprofiletyped: 'CCM/jsonprofiletyped.md'
    - options: 'CCM/options.md'
    - path: 'CCM/path.md'
    - property: 'CCM/property.md'
    - resource: 'CCM/resource.md'
    - syncfile: 'CCM/syncfile.md'
    - textrender: 'CCM/textrender.md'
    - tt::scalar: 'CCM/tt::scalar.md'
    - xmlpanprofile: 'CCM/xmlpanprofile.md'
- components:
    - accounts: 'components/accounts.md'
    - accounts::schema: 'components/accounts::schema.md'
    - afsclt: 'components/afsclt.md'
    - afsclt::schema: 'components/afsclt::schema.md'
    - aiiserver: 'components/aiiserver.md'
    - aiiserver::schema: 'components/aiiserver::schema.md'
    - altlogrotate: 'components/altlogrotate.md'
    - altlogrotate::schema: 'components/altlogrotate::schema.md'
    - amandaserver: 'components/amandaserver.md'
    - amandaserver::schema: 'components/amandaserver::schema.md'
    - authconfig: 'components/authconfig.md'
    - authconfig::schema: 'components/authconfig::schema.md'
    - autofs: 'components/autofs.md'
    - autofs::schema: 'components/autofs::schema.md'
    - ccm: 'components/ccm.md'
    - ccm::schema: 'components/ccm::schema.md'
    - cdp: 'components/cdp.md'
    - cdp::schema: 'components/cdp::schema.md'
    - ceph: 'components/ceph.md'
    - ceph::commands: 'components/ceph::commands.md'
    - ceph::compare: 'components/ceph::compare.md'
    - ceph::config: 'components/ceph::config.md'
    - ceph::crushmap: 'components/ceph::crushmap.md'
    - ceph::daemon: 'components/ceph::daemon.md'
    - ceph::schema: 'components/ceph::schema.md'
    - chkconfig: 'components/chkconfig.md'
    - chkconfig::schema: 'components/chkconfig::schema.md'
    - cron: 'components/cron.md'
    - cron::schema: 'components/cron::schema.md'
    - cups: 'components/cups.md'
    - cups::schema: 'components/cups::schema.md'
    - directoryservices: 'components/directoryservices.md'
    - directoryservices::schema: 'components/directoryservices::schema.md'
    - dirperm: 'components/dirperm.md'
    - dirperm::schema: 'components/dirperm::schema.md'
    - download: 'components/download.md'
    - download::schema: 'components/download::schema.md'
    - etcservices: 'components/etcservices.md'
    - etcservices::schema: 'components/etcservices::schema.md'
    - filecopy: 'components/filecopy.md'
    - filecopy::schema: 'components/filecopy::schema.md'
    - filesystems: 'components/filesystems.md'
    - filesystems::schema: 'components/filesystems::schema.md'
    - fmonagent: 'components/fmonagent.md'
    - fmonagent::schema: 'components/fmonagent::schema.md'
    - fstab: 'components/fstab.md'
    - fstab::schema: 'components/fstab::schema.md'
    - ganglia: 'components/ganglia.md'
    - ganglia::schema: 'components/ganglia::schema.md'
    - gmetad: 'components/gmetad.md'
    - gmetad::schema: 'components/gmetad::schema.md'
    - gmond: 'components/gmond.md'
    - gmond::schema: 'components/gmond::schema.md'
    - gpfs: 'components/gpfs.md'
    - gpfs::schema: 'components/gpfs::schema.md'
    - grub: 'components/grub.md'
    - grub::schema: 'components/grub::schema.md'
    - hostsaccess: 'components/hostsaccess.md'
    - hostsaccess::schema: 'components/hostsaccess::schema.md'
    - hostsfile: 'components/hostsfile.md'
    - hostsfile::schema: 'components/hostsfile::schema.md'
    - icinga: 'components/icinga.md'
    - icinga::schema: 'components/icinga::schema.md'
    - interactivelimits: 'components/interactivelimits.md'
    - interactivelimits::schema: 'components/interactivelimits::schema.md'
    - ipmi: 'components/ipmi.md'
    - ipmi::schema: 'components/ipmi::schema.md'
    - ips::schema: 'components/ips::schema.md'
    - iptables: 'components/iptables.md'
    - iptables::schema: 'components/iptables::schema.md'
    - ldconf: 'components/ldconf.md'
    - ldconf::schema: 'components/ldconf::schema.md'
    - libvirtd: 'components/libvirtd.md'
    - libvirtd::schema: 'components/libvirtd::schema.md'
    - mcx: 'components/mcx.md'
    - mcx::schema: 'components/mcx::schema.md'
    - metaconfig: 'components/metaconfig.md'
    - metaconfig::schema: 'components/metaconfig::schema.md'
    - modprobe: 'components/modprobe.md'
    - modprobe::schema: 'components/modprobe::schema.md'
    - mysql: 'components/mysql.md'
    - mysql::schema: 'components/mysql::schema.md'
    - nagios: 'components/nagios.md'
    - nagios::schema: 'components/nagios::schema.md'
    - named: 'components/named.md'
    - named::schema: 'components/named::schema.md'
    - network: 'components/network.md'
    - network::schema: 'components/network::schema.md'
    - nfs: 'components/nfs.md'
    - nfs::schema: 'components/nfs::schema.md'
    - nrpe: 'components/nrpe.md'
    - nrpe::schema: 'components/nrpe::schema.md'
    - nsca: 'components/nsca.md'
    - nsca::schema: 'components/nsca::schema.md'
    - nscd: 'components/nscd.md'
    - nscd::schema: 'components/nscd::schema.md'
    - nss: 'components/nss.md'
    - nss::schema: 'components/nss::schema.md'
    - ntpd: 'components/ntpd.md'
    - ntpd::schema: 'components/ntpd::schema.md'
    - ofed: 'components/ofed.md'
    - ofed::schema: 'components/ofed::schema.md'
    - openldap: 'components/openldap.md'
    - openldap::schema: 'components/openldap::schema.md'
    - opennebula: 'components/opennebula.md'
    - opennebula::commands: 'components/opennebula::commands.md'
    - opennebula::schema: 'components/opennebula::schema.md'
    - openvpn: 'components/openvpn.md'
    - openvpn::schema: 'components/openvpn::schema.md'
    - pam: 'components/pam.md'
    - pam::schema: 'components/pam::schema.md'
    - pnp4nagios: 'components/pnp4nagios.md'
    - pnp4nagios::schema: 'components/pnp4nagios::schema.md'
    - postfix: 'components/postfix.md'
    - postfix::schema: 'components/postfix::schema.md'
    - postgresql: 'components/postgresql.md'
    - postgresql::commands: 'components/postgresql::commands.md'
    - postgresql::schema: 'components/postgresql::schema.md'
    - postgresql::service: 'components/postgresql::service.md'
    - profile: 'components/profile.md'
    - profile::schema: 'components/profile::schema.md'
    - puppet: 'components/puppet.md'
    - puppet::schema: 'components/puppet::schema.md'
    - resolver: 'components/resolver.md'
    - resolver::schema: 'components/resolver::schema.md'
    - sendmail: 'components/sendmail.md'
    - sendmail::schema: 'components/sendmail::schema.md'
    - shorewall: 'components/shorewall.md'
    - shorewall::schema: 'components/shorewall::schema.md'
    - spma-run: 'components/spma-run.md'
    - spma: 'components/spma.md'
    - spma::ips: 'components/spma::ips.md'
    - spma::schema: 'components/spma::schema.md'
    - spma::yum: 'components/spma::yum.md'
    - ssh: 'components/ssh.md'
    - ssh::schema: 'components/ssh::schema.md'
    - sudo: 'components/sudo.md'
    - sudo::schema: 'components/sudo::schema.md'
    - symlink: 'components/symlink.md'
    - symlink::schema: 'components/symlink::schema.md'
    - sysconfig: 'components/sysconfig.md'
    - sysconfig::schema: 'components/sysconfig::schema.md'
    - sysctl: 'components/sysctl.md'
    - sysctl::schema: 'components/sysctl::schema.md'
    - syslog: 'components/syslog.md'
    - syslog::schema: 'components/syslog::schema.md'
    - syslogng: 'components/syslogng.md'
    - syslogng::schema: 'components/syslogng::schema.md'
    - systemd: 'components/systemd.md'
    - systemd::schema: 'components/systemd::schema.md'
    - systemd::service: 'components/systemd::service.md'
    - systemd::service::chkconfig: 'components/systemd::service::chkconfig.md'
    - systemd::service::component::chkconfig: 'components/systemd::service::component::chkconfig.md'
    - systemd::service::unit: 'components/systemd::service::unit.md'
    - systemd::systemctl: 'components/systemd::systemctl.md'
    - systemd::unitfile: 'components/systemd::unitfile.md'
    - useraccess: 'components/useraccess.md'
    - useraccess::schema: 'components/useraccess::schema.md'
    - yum::schema: 'components/yum::schema.md'

